"""Report generator for creating professional security analysis reports."""

import logging
from datetime import datetime

logger = logging.getLogger(__name__)


class ReportGenerator:
    """Generates professional Markdown security analysis reports."""

    @staticmethod
    def generate_report(
        repo_url: str,
        repo_name: str,
        findings: list[dict],
        is_approved: bool = False,
        analyzed_files: int = 0,
        total_files: int = 0,
    ) -> str:
        """Generate a professional security analysis report.

        Args:
            repo_url: URL of the analyzed repository
            repo_name: Name of the repository
            findings: List of security findings
            is_approved: Whether the report was approved
            analyzed_files: Number of files analyzed
            total_files: Total files in repository

        Returns:
            Markdown formatted report string
        """
        # Generate timestamp
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")

        # Calculate statistics
        stats = ReportGenerator._calculate_statistics(findings)

        # Generate report sections
        report_parts = []

        # Header
        report_parts.append("# Security Analysis Report")
        report_parts.append("")
        report_parts.append(f"**Repository:** [{repo_name}]({repo_url})")
        report_parts.append(f"**Analyzed:** {timestamp}")
        report_parts.append(f"**Status:** {'✅ Approved' if is_approved else '⏸️ Pending Approval'}")
        report_parts.append("")

        # Summary
        report_parts.append("## Executive Summary")
        report_parts.append("")
        report_parts.append(ReportGenerator._generate_summary(repo_name, stats, analyzed_files, total_files))
        report_parts.append("")

        # Statistics Dashboard
        report_parts.append("## Findings Summary")
        report_parts.append("")
        report_parts.append(ReportGenerator._generate_statistics_section(stats))
        report_parts.append("")

        # Findings by Severity
        if findings:
            report_parts.append("## Detailed Findings")
            report_parts.append("")
            report_parts.append(ReportGenerator._generate_findings_section(findings))
            report_parts.append("")

        # Recommendations
        report_parts.append("## Recommendations")
        report_parts.append("")
        report_parts.append(ReportGenerator._generate_recommendations(stats))
        report_parts.append("")

        # Footer
        report_parts.append("---")
        report_parts.append("*This report was generated by the Autonomous Codebase Librarian*")

        return "\n".join(report_parts)

    @staticmethod
    def _calculate_statistics(findings: list[dict]) -> dict:
        """Calculate statistics from findings.

        Args:
            findings: List of security findings

        Returns:
            Dictionary with calculated statistics
        """
        stats = {
            "critical": 0,
            "high": 0,
            "medium": 0,
            "low": 0,
            "info": 0,
            "total": len(findings),
            "by_type": {},
        }

        for finding in findings:
            severity = finding.get("severity", "info").lower()
            if severity in stats:
                stats[severity] += 1

            finding_type = finding.get("type", "vulnerability").lower()
            stats["by_type"][finding_type] = stats["by_type"].get(finding_type, 0) + 1

        return stats

    @staticmethod
    def _generate_summary(repo_name: str, stats: dict, analyzed_files: int, total_files: int) -> str:
        """Generate executive summary text.

        Args:
            repo_name: Repository name
            stats: Statistics dictionary
            analyzed_files: Number of files analyzed
            total_files: Total files in repo

        Returns:
            Summary text
        """
        severity_score = 0
        if stats["critical"] > 0:
            severity_score = 90 + min(stats["critical"] * 5, 10)
        elif stats["high"] > 0:
            severity_score = 70 + min(stats["high"] * 2, 20)
        elif stats["medium"] > 0:
            severity_score = 40 + min(stats["medium"], 30)
        elif stats["low"] > 0:
            severity_score = 20
        else:
            severity_score = 0

        if stats["total"] == 0:
            return f"No security issues detected in {repo_name}. The repository appears to follow good security practices. **Security Score: 100/100**"
        else:
            return f"""The analysis of {repo_name} identified {stats["total"]} security findings across {analyzed_files} analyzed files (out of {total_files} total files).

**Security Score: {100 - severity_score}/100**

- **Critical Issues:** {stats["critical"]} (require immediate attention)
- **High Priority Issues:** {stats["high"]} (should be addressed soon)
- **Medium Priority Issues:** {stats["medium"]} (should be reviewed)
- **Low Priority Issues:** {stats["low"]} (informational)
- **Informational:** {stats["info"]} (for awareness)"""

    @staticmethod
    def _generate_statistics_section(stats: dict) -> str:
        """Generate statistics section.

        Args:
            stats: Statistics dictionary

        Returns:
            Statistics section text
        """
        sections = []

        # Severity breakdown
        sections.append("### Severity Breakdown")
        sections.append("")
        sections.append(f"| Severity | Count |")
        sections.append("|----------|-------|")
        sections.append(f"| 🔴 Critical | {stats['critical']} |")
        sections.append(f"| 🟠 High | {stats['high']} |")
        sections.append(f"| 🟡 Medium | {stats['medium']} |")
        sections.append(f"| 🟢 Low | {stats['low']} |")
        sections.append(f"| ℹ️ Info | {stats['info']} |")
        sections.append(f"| **Total** | **{stats['total']}** |")
        sections.append("")

        return "\n".join(sections)

    @staticmethod
    def _generate_findings_section(findings: list[dict]) -> str:
        """Generate findings section grouped by severity.

        Args:
            findings: List of security findings

        Returns:
            Findings section text
        """
        sections = []

        # Group findings by severity
        severity_order = ["critical", "high", "medium", "low", "info"]
        grouped = {severity: [] for severity in severity_order}

        for finding in findings:
            severity = finding.get("severity", "info").lower()
            if severity in grouped:
                grouped[severity].append(finding)

        # Generate sections for each severity level
        severity_emoji = {
            "critical": "🔴",
            "high": "🟠",
            "medium": "🟡",
            "low": "🟢",
            "info": "ℹ️",
        }

        for severity in severity_order:
            if grouped[severity]:
                emoji = severity_emoji.get(severity, "")
                sections.append(f"### {emoji} {severity.upper().capitalize()} Severity ({len(grouped[severity])})")
                sections.append("")

                for idx, finding in enumerate(grouped[severity], 1):
                    sections.append(f"#### {idx}. {finding.get('title', 'Unknown')}")
                    sections.append("")
                    sections.append(f"**Type:** {finding.get('type', 'vulnerability')}")
                    sections.append(f"**File:** `{finding.get('file', 'unknown')}`")
                    sections.append(f"**Line:** {finding.get('line_reference', 'N/A')}")
                    sections.append(f"**CWE:** {finding.get('cwe', 'N/A')}")
                    sections.append("")
                    sections.append(f"**Description:**")
                    sections.append(f"{finding.get('description', 'No description provided')}")
                    sections.append("")
                    sections.append(f"**Recommendation:**")
                    sections.append(f"{finding.get('recommendation', 'Please review manually')}")
                    sections.append("")
                    sections.append("---")
                    sections.append("")

        return "\n".join(sections)

    @staticmethod
    def _generate_recommendations(stats: dict) -> str:
        """Generate recommendations section.

        Args:
            stats: Statistics dictionary

        Returns:
            Recommendations section text
        """
        recommendations = []

        if stats["critical"] > 0:
            recommendations.append("1. **Immediately address all critical issues** - These require urgent security fixes")

        if stats["high"] > 0:
            recommendations.append("2. **Prioritize high severity findings** - Create a timeline for remediation within the next sprint")

        if stats["medium"] > 0:
            recommendations.append("3. **Schedule medium priority fixes** - Plan these fixes for future development cycles")

        if stats["low"] > 0 or stats["info"] > 0:
            recommendations.append("4. **Review low severity issues and informational items** - Consider best practices improvements")

        if stats["total"] == 0:
            recommendations.append("1. **Continue security best practices** - Maintain current security posture with regular reviews")
            recommendations.append("2. **Implement security scanning in CI/CD** - Automate vulnerability detection")
            recommendations.append("3. **Keep dependencies updated** - Regularly update packages and libraries")
        else:
            recommendations.append("5. **Conduct regular security audits** - Re-analyze after fixes are applied")
            recommendations.append("6. **Implement automated security scanning** - Add to your CI/CD pipeline for continuous monitoring")

        return "\n".join(recommendations)
